export const TodosActionTypes = {
  COMPLETE_TODO: "COMPLETE_TODO",
  REMOVE_TODO: "REMOVE_TODO",

  INSERT_TODO_START: "INSERT_TODO_START",
  INSERT_TODO_SUCCESS: "INSERT_TODO_SUCCESS",
  INSERT_TODO_FAILURE: "INSERT_TODO_FAILURE"
};
